# Generated by Django 4.0.3 on 2022-04-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamFormFillUp_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='studentid',
            field=models.PositiveIntegerField(),
        ),
    ]
